package cx.mia.lucent.laymark.core.harness;

import cx.mia.lucent.laymark.core.scenario.ScenePlacement;
import cx.mia.lucent.laymark.core.plan.StopCondition;
import java.time.Duration;
import java.util.List;

/**
 * Everything the run sequence needs the game to do, expressed as semantic operations.
 *
 * <p>No Minecraft types cross this interface, and that is the point rather than a formality: it
 * lets the whole sequence — ordering, barriers, failure semantics, what invalidates a scenario —
 * be tested against an in-memory implementation in milliseconds. The alternative is discovering
 * an ordering bug by launching a game, which costs minutes per attempt and can only be done on a
 * machine with a GPU.
 *
 * <p>Implementations live in {@code minecraft-common}. Each operation is expected to be
 * <strong>synchronous and settled</strong> when it returns: {@link #applyPreset} returns after the
 * renderer has converged, not after the setter returned. A method that returns early would push
 * the barrier problem back into the sequence, which is exactly where it must not be.
 */
public interface HarnessPort {

    /**
     * Applies every setting and blocks until the game has settled on them.
     *
     * <p>Must apply unconditionally rather than diffing. {@code OptionInstance.set} skips its
     * update callback when the value is unchanged, so re-applying a preset for the second
     * scenario in a launch is otherwise a no-op that silently leaves the first scenario's
     * overrides live.
     */
    void applyPreset(Preset preset);

    /**
     * Reads back what the game <em>actually</em> has, which is not necessarily what was asked for.
     *
     * <p>Separate from {@link #applyPreset} because the difference is the whole point: an invalid
     * value is silently replaced by the option's default, a fullscreen request can be declined,
     * and a mod can revert a setting after it was applied.
     *
     * @param requested needed because not every setting has an effective accessor — VSync has
     *     none at all — and those are echoed back as asked rather than invented
     */
    PresetReadback readPreset(Preset requested);

    /** Creates a fresh disposable save and enters it. */
    void createWorld(WorldSpec spec);

    /**
     * Enters a disposable save that already exists, generated by an earlier scenario.
     *
     * <p>Reopened rather than kept open between scenarios, and that is the point rather than an
     * implementation detail: leaving the world loaded would leave the client's meshes built, and
     * the phase that measures streaming requires them not to be. Closing and reopening keeps the
     * region files — the generation this scenario depends on — while returning the client to the
     * state that makes streaming measurable.
     *
     * @throws HarnessException if the save is not there, which means the scenario that was supposed
     *     to generate it did not
     */
    void openWorld(WorldSpec spec);

    /**
     * Blocks until the world is genuinely ready to measure.
     *
     * @return what the barrier waited on and for how long, so two arms can be compared on the
     *     state they started from rather than assumed to have matched
     * @throws HarnessException if the barrier does not pass within the timeout. Timing out fails
     *     the run rather than proceeding: measuring an unbuilt world produces plausible numbers,
     *     and the runs that time out are the slow ones, so the error would correlate with the
     *     thing being compared.
     */
    BarrierReport awaitReady(Duration timeout);

    /**
     * Places the player, waits for the renderer to settle, and re-confirms the barrier.
     *
     * <p>For the phases that measure a steady state. Not for traversal, where the settling is the
     * thing being measured — see {@link #teleport}.
     */
    void position(Pose pose);

    /**
     * Moves the player and returns immediately.
     *
     * <p>Separate from {@link #position} because for {@link cx.mia.lucent.laymark.core.Phase#UNGENERATED_TRAVERSAL}
     * <strong>the teleport is the measured event</strong>. A capture has to bracket the arrival,
     * so nothing may block between opening the window and the move — and the settle-and-rebarrier
     * that {@code position} performs would pay the entire cost before the window opened.
     */
    void teleport(Pose pose);

    /**
     * Blocks until a stop condition is met, with a capture already open.
     *
     * <p>Split out for the same reason as {@link #teleport}: a phase whose measured event happens
     * mid-window needs the window opened, the event triggered, and only then the wait.
     */
    void awaitStop(StopCondition stop);

    /**
     * Whether the region around the pose has never been generated.
     *
     * <p>The negative precondition for {@link cx.mia.lucent.laymark.core.Phase#UNGENERATED_TRAVERSAL}.
     * Measuring generation destroys the thing being measured, so a repetition that finds its
     * target already generated has to fail rather than proceed — it would complete normally and
     * report flatteringly good numbers.
     */
    boolean targetIsUngenerated(Pose pose);

    /**
     * Whether the client currently holds no built sections for the region around the pose.
     *
     * <p>The negative precondition for {@link cx.mia.lucent.laymark.core.Phase#GENERATED_STREAMING}.
     * Deliberately not a claim about disk: after generation the region files sit in the OS page
     * cache and a mod cannot portably evict them. This is about the client's meshes.
     */
    boolean targetHasNoBuiltSections(Pose pose);

    /**
     * Pins the game rules that would otherwise vary inside a capture.
     *
     * <p>Time, weather and mob spawning all advance during a measured window at vanilla defaults --
     * three variables moving independently of the thing under test, in both arms but never
     * identically. Applied post-join because world creation takes no game rules.
     */
    void pinGameRules();

    /** Places scene geometry. Runs before any barrier, since it changes what there is to build. */
    void placeContent(List<ScenePlacement> content);

    /**
     * Records every channel for the given duration and returns the raw series.
     *
     * <p>All channels, always. Deciding per scenario which ones to open would save nothing worth
     * having -- they are field reads on hot paths that already exist -- and would guarantee that
     * the one run nobody thought to instrument is the one that turns out to matter.
     *
     * <p>Takes the whole stop condition rather than a duration because two of the three kinds end
     * on the game making progress, which only the implementation can observe.
     *
     * @throws HarnessException if the target is not reached within the condition's timeout
     */
    Measurement capture(StopCondition stop);

    /**
     * Opens a capture window without deciding when it ends.
     *
     * <p>Split out for spawn generation, whose end is not a target anyone configures — it is the
     * readiness barrier passing. The window has to be open across {@link #createWorld}, so nothing
     * can be waited on in between.
     */
    void beginCapture();

    /** Closes a window opened by {@link #beginCapture}. */
    Measurement endCapture();

    /**
     * Saves and leaves the world, releasing its lock.
     *
     * <p>Must tolerate being called when no world is open. It runs in the cleanup path of a
     * repetition that may have failed before, during or after {@link #createWorld}, and a cleanup
     * step that throws on the uninteresting case buries the failure that caused it.
     */
    void closeWorld();

    /** Deletes a disposable save and its region files. Silent when there is nothing to delete. */
    void deleteWorld(String levelId);
}
